### ISSUE TITLE
Release 0.6.6.2

### ISSUE THREAD

**Issue by echatav** [ryantm/hdbc-mysql#17]
Is there anything preventing hdbc-mysql-0.6.6.2 from being released on hackage? The current version on  hackage does not build with cabal-install-1.22.6.0.

```
Failed to install HDBC-mysql-0.6.6.1
Build log ( /Users/hephaestus/Documents/Programming/Haskell/blah/.cabal-sandbox/logs/HDBC-mysql-0.6.6.1.log ):
cabal: Error: some packages failed to install:
HDBC-mysql-0.6.6.1 failed during the configure step. The exception was:
user error ('/Applications/ghc-7.10.1.app/Contents/bin/ghc' exited with an
error:

/var/folders/9d/v7bp0jtd5z30m8ptpk69b7sc0000gq/T/cabal-tmp-9063/HDBC-mysql-0.6.6.1/dist/dist-sandbox-bdd49036/setup/setup.hs:31:7:
Couldn't match type ‘IO (Maybe FilePath)’
with ‘ProgramSearchPath -> IO (Maybe FilePath)’
Expected type: IO (Maybe FilePath)
-> (Maybe FilePath -> IO (Maybe FilePath))
-> ProgramSearchPath
-> IO (Maybe FilePath)
Actual type: IO (Maybe FilePath)
-> (Maybe FilePath -> IO (Maybe FilePath)) -> IO (Maybe FilePath)
In a stmt of a 'do' block:
mysql_config <- findProgramOnPath "mysql_config" verbosity
In the expression:
do { mysql_config <- findProgramOnPath "mysql_config" verbosity;
mysql_config5 <- findProgramOnPath "mysql_config5" verbosity;
return (mysql_config `mplus` mysql_config5) }
In the ‘programFindLocation’ field of a record
)
```

The version in the repository, hdbc-mysql-0.6.6.2, installs just fine.

**Comment by herberteuler** [comment]
With [this patch](http://data.gpo.zugaina.org/haskell/dev-haskell/hdbc-mysql/files/hdbc-mysql-0.6.6.1-cabal-1.18.patch), you can build it in a sandbox:

```shell
$ cabal sandbox add-source /path/to/patched/source
$ cabal install --only-dependencies
```

**Comment by achudnov** [comment]
I was wondering if it makes sense to rewrite this package using `mysql` (https://github.com/bos/mysql) which seems to be (a bit) better maintained. Has anyone looked into it?

**Comment by ryantm** [comment]
@bos Can this be updated, or would you be willing to add me to the hackage maintainers? https://wiki.haskell.org/Taking_over_a_package My hackage username is ryantm

**Comment by NoICE** [comment]
Please push this to hackage :-(

**Comment by ryantm** [comment]
I am still willing to help out as a package maintainer. Since there hasn't been a response from the current maintainer, I think it makes sense to make a (possibly-temporary) fork. Any suggestions on a good name?

**Comment by junix** [comment]
I met the same problem, and modified setup.hs 
      
      --return (mysql_config `mplus` mysql_config5)
      case mysql_config of
        Just c -> return (Just (c , [c]))

seem work OK

**Comment by gbaz** [comment]
I hesitate to suggest this because I know that @bos does show up on occasion and is just very occupied with various things. But if he remains unresponsive here, @ryantm may just want to initiate the non-contactable maintainer package maintainer process as described on the page he linked? This seems especially reasonable as this package has a long history prior to bryan's involvement, so it really is just handing the maintainer reigns over from one busy individual to another person with more interest/appetite at this time.

**Comment by ryantm** [comment]
@gbaz Thanks for the suggestion. I tried sending bos a private email just now to complete the first step.

**Comment by ryantm** [comment]
bos has transferred the repository to me and given me maintainer access on Hackage. I will try to release version 0.6.6.2 soon.

**Comment by ryantm** [comment]
I made a release that is just 0.6.6.2 I was able to run very simple Test.hs script and it worked, but I would appreciate it if other people could test it out, since I'm am just learning this codebase and I was not able to compile the testsrc test suite.

**Comment by ryantm** [comment]
I tested this out on Ubuntu and NixOS using GHC 7.10.1 and Cabal 1.24 and it works fine, so I'm closing this. The master branch development has advanced to requiring GHC 8.0.1 and Cabal 1.24. I am closing this issue.
