### ISSUE TITLE
Stackage maybe?

### ISSUE THREAD

**Issue by kanishka-azimi** [ryantm/hdbc-mysql#24]
I appreciate you considering registering this library on Stackage. No worries if you prefer not to. You close this issue either way after reading it.

**Comment by ryantm** [comment]
@kanishka-azimi I registered it with Stackage a while ago: https://github.com/fpco/stackage/blob/master/build-constraints.yaml#L2772

Is there something else I need to do to make it useful to you?

Ryan

**Comment by ryantm** [comment]
https://www.stackage.org/package/HDBC-mysql says it's not in any snapshots. Maybe it's because the capitalization is incorrect? I'm not that familiar with how Stackage works.

**Comment by kanishka-azimi** [comment]
I think it was booted somehow, but I can't find a record yet of when or why
they booted it. I will see if I can find a travis build history where
hdbc-mysql was present or absent.

Maybe the PR you made needed to be case sensitive as you note.

**Comment by ryantm** [comment]
If they booted it, I'd expect they would have emailed the maintainer about it and/or removed it from the build-constraints.yaml.

**Comment by kanishka-azimi** [comment]
https://www.stackage.org/nightly-2017-04-02/cabal.config?global=true
(this is redirected from nightly)

I tried a few others like lts, lts-8 . I also tried close to when the PR
was merged. So, it looks like it never got it, probably because of the
capitalization

**Comment by ryantm** [comment]
The problem was the capitalization. My PR was merged, and now it is in Stackage Nightly. Thanks for raising this issue!

Ryan
