### ISSUE TITLE
Small contributions needed?

### ISSUE THREAD

**Issue by kanishka-azimi** [ryantm/hdbc-mysql#25]
Are there any bugs or tests or simple features you want added? I might have some limited free time.

**Comment by ryantm** [comment]
Thanks for your interest! Definitely more tests would be exciting, especially failing ones that demonstrate the problems open in the other GitHub issues.

As for documentation, more documentation that shows how to use this independently from reading the HDBC documentation, or better links to HDBC documentation would be helpful.

Ryan

**Comment by kanishka-azimi** [comment]
Noted.

**Comment by kanishka-azimi** [comment]
This has fallen off my radar...
