### ISSUE TITLE
Use of programFindLocation in Setup.hs is incompatible with Cabal 1.18

### ISSUE THREAD

**Issue by redfox-dennis-gosnell** [ryantm/hdbc-mysql#9]
I am getting an error compiling hdbc-mysql with cabal 1.18.  It looks to be the same error reported here: https://github.com/hdbc/hdbc-postgresql/issues/30.

The fix seems to be here:
https://github.com/scrive/hdbc-postgresql/commit/e9b2fbab07b8f55ae6a9e120ab0b98c433842a8b

**Comment by NoICE** [comment]
I'm glad someone patched this, but ... why it isn't on hackage yet? How can I use the patch if I use cabal sandboxes? :/

**Comment by eyeinsky** [comment]
This issue was fixed with #11

**Comment by NoICE** [comment]
Cool :-)
